/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as WebrtcRouteImport } from "./routes/webrtc"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as ExploreRouteImport } from "./routes/explore"
import { Route as MessagesRouteRouteImport } from "./routes/messages/route"
import { Route as FriendsRouteRouteImport } from "./routes/friends/route"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as MessagesIndexRouteImport } from "./routes/messages/index"
import { Route as FriendsIndexRouteImport } from "./routes/friends/index"
import { Route as MessagesIdRouteImport } from "./routes/messages/$id"
import { Route as ServersIdRouteRouteImport } from "./routes/servers/$id/route"
import { Route as ServersIdIndexRouteImport } from "./routes/servers/$id/index"
import { Route as ServersIdSettingsRouteImport } from "./routes/servers/$id/settings"

const WebrtcRoute = WebrtcRouteImport.update({
  id: "/webrtc",
  path: "/webrtc",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: "/explore",
  path: "/explore",
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRouteRoute = MessagesRouteRouteImport.update({
  id: "/messages",
  path: "/messages",
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRouteRoute = FriendsRouteRouteImport.update({
  id: "/friends",
  path: "/friends",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesIndexRoute = MessagesIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => MessagesRouteRoute,
} as any)
const FriendsIndexRoute = FriendsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => FriendsRouteRoute,
} as any)
const MessagesIdRoute = MessagesIdRouteImport.update({
  id: "/$id",
  path: "/$id",
  getParentRoute: () => MessagesRouteRoute,
} as any)
const ServersIdRouteRoute = ServersIdRouteRouteImport.update({
  id: "/servers/$id",
  path: "/servers/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const ServersIdIndexRoute = ServersIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ServersIdRouteRoute,
} as any)
const ServersIdSettingsRoute = ServersIdSettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => ServersIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/friends": typeof FriendsRouteRouteWithChildren
  "/messages": typeof MessagesRouteRouteWithChildren
  "/explore": typeof ExploreRoute
  "/settings": typeof SettingsRoute
  "/webrtc": typeof WebrtcRoute
  "/servers/$id": typeof ServersIdRouteRouteWithChildren
  "/messages/$id": typeof MessagesIdRoute
  "/friends/": typeof FriendsIndexRoute
  "/messages/": typeof MessagesIndexRoute
  "/servers/$id/settings": typeof ServersIdSettingsRoute
  "/servers/$id/": typeof ServersIdIndexRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/explore": typeof ExploreRoute
  "/settings": typeof SettingsRoute
  "/webrtc": typeof WebrtcRoute
  "/messages/$id": typeof MessagesIdRoute
  "/friends": typeof FriendsIndexRoute
  "/messages": typeof MessagesIndexRoute
  "/servers/$id/settings": typeof ServersIdSettingsRoute
  "/servers/$id": typeof ServersIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/friends": typeof FriendsRouteRouteWithChildren
  "/messages": typeof MessagesRouteRouteWithChildren
  "/explore": typeof ExploreRoute
  "/settings": typeof SettingsRoute
  "/webrtc": typeof WebrtcRoute
  "/servers/$id": typeof ServersIdRouteRouteWithChildren
  "/messages/$id": typeof MessagesIdRoute
  "/friends/": typeof FriendsIndexRoute
  "/messages/": typeof MessagesIndexRoute
  "/servers/$id/settings": typeof ServersIdSettingsRoute
  "/servers/$id/": typeof ServersIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/friends"
    | "/messages"
    | "/explore"
    | "/settings"
    | "/webrtc"
    | "/servers/$id"
    | "/messages/$id"
    | "/friends/"
    | "/messages/"
    | "/servers/$id/settings"
    | "/servers/$id/"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/explore"
    | "/settings"
    | "/webrtc"
    | "/messages/$id"
    | "/friends"
    | "/messages"
    | "/servers/$id/settings"
    | "/servers/$id"
  id:
    | "__root__"
    | "/"
    | "/friends"
    | "/messages"
    | "/explore"
    | "/settings"
    | "/webrtc"
    | "/servers/$id"
    | "/messages/$id"
    | "/friends/"
    | "/messages/"
    | "/servers/$id/settings"
    | "/servers/$id/"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FriendsRouteRoute: typeof FriendsRouteRouteWithChildren
  MessagesRouteRoute: typeof MessagesRouteRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  SettingsRoute: typeof SettingsRoute
  WebrtcRoute: typeof WebrtcRoute
  ServersIdRouteRoute: typeof ServersIdRouteRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/webrtc": {
      id: "/webrtc"
      path: "/webrtc"
      fullPath: "/webrtc"
      preLoaderRoute: typeof WebrtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/explore": {
      id: "/explore"
      path: "/explore"
      fullPath: "/explore"
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/messages": {
      id: "/messages"
      path: "/messages"
      fullPath: "/messages"
      preLoaderRoute: typeof MessagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/friends": {
      id: "/friends"
      path: "/friends"
      fullPath: "/friends"
      preLoaderRoute: typeof FriendsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/messages/": {
      id: "/messages/"
      path: "/"
      fullPath: "/messages/"
      preLoaderRoute: typeof MessagesIndexRouteImport
      parentRoute: typeof MessagesRouteRoute
    }
    "/friends/": {
      id: "/friends/"
      path: "/"
      fullPath: "/friends/"
      preLoaderRoute: typeof FriendsIndexRouteImport
      parentRoute: typeof FriendsRouteRoute
    }
    "/messages/$id": {
      id: "/messages/$id"
      path: "/$id"
      fullPath: "/messages/$id"
      preLoaderRoute: typeof MessagesIdRouteImport
      parentRoute: typeof MessagesRouteRoute
    }
    "/servers/$id": {
      id: "/servers/$id"
      path: "/servers/$id"
      fullPath: "/servers/$id"
      preLoaderRoute: typeof ServersIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/servers/$id/": {
      id: "/servers/$id/"
      path: "/"
      fullPath: "/servers/$id/"
      preLoaderRoute: typeof ServersIdIndexRouteImport
      parentRoute: typeof ServersIdRouteRoute
    }
    "/servers/$id/settings": {
      id: "/servers/$id/settings"
      path: "/settings"
      fullPath: "/servers/$id/settings"
      preLoaderRoute: typeof ServersIdSettingsRouteImport
      parentRoute: typeof ServersIdRouteRoute
    }
  }
}

interface FriendsRouteRouteChildren {
  FriendsIndexRoute: typeof FriendsIndexRoute
}

const FriendsRouteRouteChildren: FriendsRouteRouteChildren = {
  FriendsIndexRoute: FriendsIndexRoute,
}

const FriendsRouteRouteWithChildren = FriendsRouteRoute._addFileChildren(
  FriendsRouteRouteChildren,
)

interface MessagesRouteRouteChildren {
  MessagesIdRoute: typeof MessagesIdRoute
  MessagesIndexRoute: typeof MessagesIndexRoute
}

const MessagesRouteRouteChildren: MessagesRouteRouteChildren = {
  MessagesIdRoute: MessagesIdRoute,
  MessagesIndexRoute: MessagesIndexRoute,
}

const MessagesRouteRouteWithChildren = MessagesRouteRoute._addFileChildren(
  MessagesRouteRouteChildren,
)

interface ServersIdRouteRouteChildren {
  ServersIdSettingsRoute: typeof ServersIdSettingsRoute
  ServersIdIndexRoute: typeof ServersIdIndexRoute
}

const ServersIdRouteRouteChildren: ServersIdRouteRouteChildren = {
  ServersIdSettingsRoute: ServersIdSettingsRoute,
  ServersIdIndexRoute: ServersIdIndexRoute,
}

const ServersIdRouteRouteWithChildren = ServersIdRouteRoute._addFileChildren(
  ServersIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FriendsRouteRoute: FriendsRouteRouteWithChildren,
  MessagesRouteRoute: MessagesRouteRouteWithChildren,
  ExploreRoute: ExploreRoute,
  SettingsRoute: SettingsRoute,
  WebrtcRoute: WebrtcRoute,
  ServersIdRouteRoute: ServersIdRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
