/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as ExploreRouteImport } from "./routes/explore"
import { Route as MessagesRouteRouteImport } from "./routes/messages/route"
import { Route as FriendsRouteRouteImport } from "./routes/friends/route"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as FriendsIndexRouteImport } from "./routes/friends/index"
import { Route as InvitationsInvitationIdRouteImport } from "./routes/invitations/$invitationId"
import { Route as FriendsRequestsRouteImport } from "./routes/friends/requests"
import { Route as ServersIdRouteRouteImport } from "./routes/servers/$id/route"
import { Route as ServersIdIndexRouteImport } from "./routes/servers/$id/index"
import { Route as ServersIdSettingsRouteRouteImport } from "./routes/servers/$id/settings/route"
import { Route as ServersIdSettingsIndexRouteImport } from "./routes/servers/$id/settings/index"
import { Route as ServersIdChannelIdIndexRouteImport } from "./routes/servers/$id/$channelId/index"
import { Route as ServersIdSettingsRolesRouteRouteImport } from "./routes/servers/$id/settings/roles/route"
import { Route as ServersIdSettingsRolesNewRouteImport } from "./routes/servers/$id/settings/roles/new"
import { Route as ServersIdSettingsRolesRoleIdRouteRouteImport } from "./routes/servers/$id/settings/roles/$roleId/route"
import { Route as ServersIdSettingsRolesRoleIdPermissionsRouteImport } from "./routes/servers/$id/settings/roles/$roleId/permissions"
import { Route as ServersIdSettingsRolesRoleIdMembersRouteImport } from "./routes/servers/$id/settings/roles/$roleId/members"

const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: "/explore",
  path: "/explore",
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRouteRoute = MessagesRouteRouteImport.update({
  id: "/messages",
  path: "/messages",
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRouteRoute = FriendsRouteRouteImport.update({
  id: "/friends",
  path: "/friends",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsIndexRoute = FriendsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => FriendsRouteRoute,
} as any)
const InvitationsInvitationIdRoute = InvitationsInvitationIdRouteImport.update({
  id: "/invitations/$invitationId",
  path: "/invitations/$invitationId",
  getParentRoute: () => rootRouteImport,
} as any)
const FriendsRequestsRoute = FriendsRequestsRouteImport.update({
  id: "/requests",
  path: "/requests",
  getParentRoute: () => FriendsRouteRoute,
} as any)
const ServersIdRouteRoute = ServersIdRouteRouteImport.update({
  id: "/servers/$id",
  path: "/servers/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const ServersIdIndexRoute = ServersIdIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ServersIdRouteRoute,
} as any)
const ServersIdSettingsRouteRoute = ServersIdSettingsRouteRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => ServersIdRouteRoute,
} as any)
const ServersIdSettingsIndexRoute = ServersIdSettingsIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ServersIdSettingsRouteRoute,
} as any)
const ServersIdChannelIdIndexRoute = ServersIdChannelIdIndexRouteImport.update({
  id: "/$channelId/",
  path: "/$channelId/",
  getParentRoute: () => ServersIdRouteRoute,
} as any)
const ServersIdSettingsRolesRouteRoute =
  ServersIdSettingsRolesRouteRouteImport.update({
    id: "/roles",
    path: "/roles",
    getParentRoute: () => ServersIdSettingsRouteRoute,
  } as any)
const ServersIdSettingsRolesNewRoute =
  ServersIdSettingsRolesNewRouteImport.update({
    id: "/new",
    path: "/new",
    getParentRoute: () => ServersIdSettingsRolesRouteRoute,
  } as any)
const ServersIdSettingsRolesRoleIdRouteRoute =
  ServersIdSettingsRolesRoleIdRouteRouteImport.update({
    id: "/$roleId",
    path: "/$roleId",
    getParentRoute: () => ServersIdSettingsRolesRouteRoute,
  } as any)
const ServersIdSettingsRolesRoleIdPermissionsRoute =
  ServersIdSettingsRolesRoleIdPermissionsRouteImport.update({
    id: "/permissions",
    path: "/permissions",
    getParentRoute: () => ServersIdSettingsRolesRoleIdRouteRoute,
  } as any)
const ServersIdSettingsRolesRoleIdMembersRoute =
  ServersIdSettingsRolesRoleIdMembersRouteImport.update({
    id: "/members",
    path: "/members",
    getParentRoute: () => ServersIdSettingsRolesRoleIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/friends": typeof FriendsRouteRouteWithChildren
  "/messages": typeof MessagesRouteRoute
  "/explore": typeof ExploreRoute
  "/settings": typeof SettingsRoute
  "/servers/$id": typeof ServersIdRouteRouteWithChildren
  "/friends/requests": typeof FriendsRequestsRoute
  "/invitations/$invitationId": typeof InvitationsInvitationIdRoute
  "/friends/": typeof FriendsIndexRoute
  "/servers/$id/settings": typeof ServersIdSettingsRouteRouteWithChildren
  "/servers/$id/": typeof ServersIdIndexRoute
  "/servers/$id/settings/roles": typeof ServersIdSettingsRolesRouteRouteWithChildren
  "/servers/$id/$channelId/": typeof ServersIdChannelIdIndexRoute
  "/servers/$id/settings/": typeof ServersIdSettingsIndexRoute
  "/servers/$id/settings/roles/$roleId": typeof ServersIdSettingsRolesRoleIdRouteRouteWithChildren
  "/servers/$id/settings/roles/new": typeof ServersIdSettingsRolesNewRoute
  "/servers/$id/settings/roles/$roleId/members": typeof ServersIdSettingsRolesRoleIdMembersRoute
  "/servers/$id/settings/roles/$roleId/permissions": typeof ServersIdSettingsRolesRoleIdPermissionsRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/messages": typeof MessagesRouteRoute
  "/explore": typeof ExploreRoute
  "/settings": typeof SettingsRoute
  "/friends/requests": typeof FriendsRequestsRoute
  "/invitations/$invitationId": typeof InvitationsInvitationIdRoute
  "/friends": typeof FriendsIndexRoute
  "/servers/$id": typeof ServersIdIndexRoute
  "/servers/$id/settings/roles": typeof ServersIdSettingsRolesRouteRouteWithChildren
  "/servers/$id/$channelId": typeof ServersIdChannelIdIndexRoute
  "/servers/$id/settings": typeof ServersIdSettingsIndexRoute
  "/servers/$id/settings/roles/$roleId": typeof ServersIdSettingsRolesRoleIdRouteRouteWithChildren
  "/servers/$id/settings/roles/new": typeof ServersIdSettingsRolesNewRoute
  "/servers/$id/settings/roles/$roleId/members": typeof ServersIdSettingsRolesRoleIdMembersRoute
  "/servers/$id/settings/roles/$roleId/permissions": typeof ServersIdSettingsRolesRoleIdPermissionsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/friends": typeof FriendsRouteRouteWithChildren
  "/messages": typeof MessagesRouteRoute
  "/explore": typeof ExploreRoute
  "/settings": typeof SettingsRoute
  "/servers/$id": typeof ServersIdRouteRouteWithChildren
  "/friends/requests": typeof FriendsRequestsRoute
  "/invitations/$invitationId": typeof InvitationsInvitationIdRoute
  "/friends/": typeof FriendsIndexRoute
  "/servers/$id/settings": typeof ServersIdSettingsRouteRouteWithChildren
  "/servers/$id/": typeof ServersIdIndexRoute
  "/servers/$id/settings/roles": typeof ServersIdSettingsRolesRouteRouteWithChildren
  "/servers/$id/$channelId/": typeof ServersIdChannelIdIndexRoute
  "/servers/$id/settings/": typeof ServersIdSettingsIndexRoute
  "/servers/$id/settings/roles/$roleId": typeof ServersIdSettingsRolesRoleIdRouteRouteWithChildren
  "/servers/$id/settings/roles/new": typeof ServersIdSettingsRolesNewRoute
  "/servers/$id/settings/roles/$roleId/members": typeof ServersIdSettingsRolesRoleIdMembersRoute
  "/servers/$id/settings/roles/$roleId/permissions": typeof ServersIdSettingsRolesRoleIdPermissionsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/friends"
    | "/messages"
    | "/explore"
    | "/settings"
    | "/servers/$id"
    | "/friends/requests"
    | "/invitations/$invitationId"
    | "/friends/"
    | "/servers/$id/settings"
    | "/servers/$id/"
    | "/servers/$id/settings/roles"
    | "/servers/$id/$channelId/"
    | "/servers/$id/settings/"
    | "/servers/$id/settings/roles/$roleId"
    | "/servers/$id/settings/roles/new"
    | "/servers/$id/settings/roles/$roleId/members"
    | "/servers/$id/settings/roles/$roleId/permissions"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/messages"
    | "/explore"
    | "/settings"
    | "/friends/requests"
    | "/invitations/$invitationId"
    | "/friends"
    | "/servers/$id"
    | "/servers/$id/settings/roles"
    | "/servers/$id/$channelId"
    | "/servers/$id/settings"
    | "/servers/$id/settings/roles/$roleId"
    | "/servers/$id/settings/roles/new"
    | "/servers/$id/settings/roles/$roleId/members"
    | "/servers/$id/settings/roles/$roleId/permissions"
  id:
    | "__root__"
    | "/"
    | "/friends"
    | "/messages"
    | "/explore"
    | "/settings"
    | "/servers/$id"
    | "/friends/requests"
    | "/invitations/$invitationId"
    | "/friends/"
    | "/servers/$id/settings"
    | "/servers/$id/"
    | "/servers/$id/settings/roles"
    | "/servers/$id/$channelId/"
    | "/servers/$id/settings/"
    | "/servers/$id/settings/roles/$roleId"
    | "/servers/$id/settings/roles/new"
    | "/servers/$id/settings/roles/$roleId/members"
    | "/servers/$id/settings/roles/$roleId/permissions"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  FriendsRouteRoute: typeof FriendsRouteRouteWithChildren
  MessagesRouteRoute: typeof MessagesRouteRoute
  ExploreRoute: typeof ExploreRoute
  SettingsRoute: typeof SettingsRoute
  ServersIdRouteRoute: typeof ServersIdRouteRouteWithChildren
  InvitationsInvitationIdRoute: typeof InvitationsInvitationIdRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/explore": {
      id: "/explore"
      path: "/explore"
      fullPath: "/explore"
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/messages": {
      id: "/messages"
      path: "/messages"
      fullPath: "/messages"
      preLoaderRoute: typeof MessagesRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/friends": {
      id: "/friends"
      path: "/friends"
      fullPath: "/friends"
      preLoaderRoute: typeof FriendsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/friends/": {
      id: "/friends/"
      path: "/"
      fullPath: "/friends/"
      preLoaderRoute: typeof FriendsIndexRouteImport
      parentRoute: typeof FriendsRouteRoute
    }
    "/invitations/$invitationId": {
      id: "/invitations/$invitationId"
      path: "/invitations/$invitationId"
      fullPath: "/invitations/$invitationId"
      preLoaderRoute: typeof InvitationsInvitationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/friends/requests": {
      id: "/friends/requests"
      path: "/requests"
      fullPath: "/friends/requests"
      preLoaderRoute: typeof FriendsRequestsRouteImport
      parentRoute: typeof FriendsRouteRoute
    }
    "/servers/$id": {
      id: "/servers/$id"
      path: "/servers/$id"
      fullPath: "/servers/$id"
      preLoaderRoute: typeof ServersIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/servers/$id/": {
      id: "/servers/$id/"
      path: "/"
      fullPath: "/servers/$id/"
      preLoaderRoute: typeof ServersIdIndexRouteImport
      parentRoute: typeof ServersIdRouteRoute
    }
    "/servers/$id/settings": {
      id: "/servers/$id/settings"
      path: "/settings"
      fullPath: "/servers/$id/settings"
      preLoaderRoute: typeof ServersIdSettingsRouteRouteImport
      parentRoute: typeof ServersIdRouteRoute
    }
    "/servers/$id/settings/": {
      id: "/servers/$id/settings/"
      path: "/"
      fullPath: "/servers/$id/settings/"
      preLoaderRoute: typeof ServersIdSettingsIndexRouteImport
      parentRoute: typeof ServersIdSettingsRouteRoute
    }
    "/servers/$id/$channelId/": {
      id: "/servers/$id/$channelId/"
      path: "/$channelId"
      fullPath: "/servers/$id/$channelId/"
      preLoaderRoute: typeof ServersIdChannelIdIndexRouteImport
      parentRoute: typeof ServersIdRouteRoute
    }
    "/servers/$id/settings/roles": {
      id: "/servers/$id/settings/roles"
      path: "/roles"
      fullPath: "/servers/$id/settings/roles"
      preLoaderRoute: typeof ServersIdSettingsRolesRouteRouteImport
      parentRoute: typeof ServersIdSettingsRouteRoute
    }
    "/servers/$id/settings/roles/new": {
      id: "/servers/$id/settings/roles/new"
      path: "/new"
      fullPath: "/servers/$id/settings/roles/new"
      preLoaderRoute: typeof ServersIdSettingsRolesNewRouteImport
      parentRoute: typeof ServersIdSettingsRolesRouteRoute
    }
    "/servers/$id/settings/roles/$roleId": {
      id: "/servers/$id/settings/roles/$roleId"
      path: "/$roleId"
      fullPath: "/servers/$id/settings/roles/$roleId"
      preLoaderRoute: typeof ServersIdSettingsRolesRoleIdRouteRouteImport
      parentRoute: typeof ServersIdSettingsRolesRouteRoute
    }
    "/servers/$id/settings/roles/$roleId/permissions": {
      id: "/servers/$id/settings/roles/$roleId/permissions"
      path: "/permissions"
      fullPath: "/servers/$id/settings/roles/$roleId/permissions"
      preLoaderRoute: typeof ServersIdSettingsRolesRoleIdPermissionsRouteImport
      parentRoute: typeof ServersIdSettingsRolesRoleIdRouteRoute
    }
    "/servers/$id/settings/roles/$roleId/members": {
      id: "/servers/$id/settings/roles/$roleId/members"
      path: "/members"
      fullPath: "/servers/$id/settings/roles/$roleId/members"
      preLoaderRoute: typeof ServersIdSettingsRolesRoleIdMembersRouteImport
      parentRoute: typeof ServersIdSettingsRolesRoleIdRouteRoute
    }
  }
}

interface FriendsRouteRouteChildren {
  FriendsRequestsRoute: typeof FriendsRequestsRoute
  FriendsIndexRoute: typeof FriendsIndexRoute
}

const FriendsRouteRouteChildren: FriendsRouteRouteChildren = {
  FriendsRequestsRoute: FriendsRequestsRoute,
  FriendsIndexRoute: FriendsIndexRoute,
}

const FriendsRouteRouteWithChildren = FriendsRouteRoute._addFileChildren(
  FriendsRouteRouteChildren,
)

interface ServersIdSettingsRolesRoleIdRouteRouteChildren {
  ServersIdSettingsRolesRoleIdMembersRoute: typeof ServersIdSettingsRolesRoleIdMembersRoute
  ServersIdSettingsRolesRoleIdPermissionsRoute: typeof ServersIdSettingsRolesRoleIdPermissionsRoute
}

const ServersIdSettingsRolesRoleIdRouteRouteChildren: ServersIdSettingsRolesRoleIdRouteRouteChildren =
  {
    ServersIdSettingsRolesRoleIdMembersRoute:
      ServersIdSettingsRolesRoleIdMembersRoute,
    ServersIdSettingsRolesRoleIdPermissionsRoute:
      ServersIdSettingsRolesRoleIdPermissionsRoute,
  }

const ServersIdSettingsRolesRoleIdRouteRouteWithChildren =
  ServersIdSettingsRolesRoleIdRouteRoute._addFileChildren(
    ServersIdSettingsRolesRoleIdRouteRouteChildren,
  )

interface ServersIdSettingsRolesRouteRouteChildren {
  ServersIdSettingsRolesRoleIdRouteRoute: typeof ServersIdSettingsRolesRoleIdRouteRouteWithChildren
  ServersIdSettingsRolesNewRoute: typeof ServersIdSettingsRolesNewRoute
}

const ServersIdSettingsRolesRouteRouteChildren: ServersIdSettingsRolesRouteRouteChildren =
  {
    ServersIdSettingsRolesRoleIdRouteRoute:
      ServersIdSettingsRolesRoleIdRouteRouteWithChildren,
    ServersIdSettingsRolesNewRoute: ServersIdSettingsRolesNewRoute,
  }

const ServersIdSettingsRolesRouteRouteWithChildren =
  ServersIdSettingsRolesRouteRoute._addFileChildren(
    ServersIdSettingsRolesRouteRouteChildren,
  )

interface ServersIdSettingsRouteRouteChildren {
  ServersIdSettingsRolesRouteRoute: typeof ServersIdSettingsRolesRouteRouteWithChildren
  ServersIdSettingsIndexRoute: typeof ServersIdSettingsIndexRoute
}

const ServersIdSettingsRouteRouteChildren: ServersIdSettingsRouteRouteChildren =
  {
    ServersIdSettingsRolesRouteRoute:
      ServersIdSettingsRolesRouteRouteWithChildren,
    ServersIdSettingsIndexRoute: ServersIdSettingsIndexRoute,
  }

const ServersIdSettingsRouteRouteWithChildren =
  ServersIdSettingsRouteRoute._addFileChildren(
    ServersIdSettingsRouteRouteChildren,
  )

interface ServersIdRouteRouteChildren {
  ServersIdSettingsRouteRoute: typeof ServersIdSettingsRouteRouteWithChildren
  ServersIdIndexRoute: typeof ServersIdIndexRoute
  ServersIdChannelIdIndexRoute: typeof ServersIdChannelIdIndexRoute
}

const ServersIdRouteRouteChildren: ServersIdRouteRouteChildren = {
  ServersIdSettingsRouteRoute: ServersIdSettingsRouteRouteWithChildren,
  ServersIdIndexRoute: ServersIdIndexRoute,
  ServersIdChannelIdIndexRoute: ServersIdChannelIdIndexRoute,
}

const ServersIdRouteRouteWithChildren = ServersIdRouteRoute._addFileChildren(
  ServersIdRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  FriendsRouteRoute: FriendsRouteRouteWithChildren,
  MessagesRouteRoute: MessagesRouteRoute,
  ExploreRoute: ExploreRoute,
  SettingsRoute: SettingsRoute,
  ServersIdRouteRoute: ServersIdRouteRouteWithChildren,
  InvitationsInvitationIdRoute: InvitationsInvitationIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
