/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as WebrtcRouteImport } from "./routes/webrtc"
import { Route as SigninRouteImport } from "./routes/signin"
import { Route as SettingsRouteImport } from "./routes/settings"
import { Route as NotificationsRouteImport } from "./routes/notifications"
import { Route as MessagesRouteImport } from "./routes/messages"
import { Route as ExploreRouteImport } from "./routes/explore"
import { Route as AuthRouteImport } from "./routes/auth"
import { Route as IndexRouteImport } from "./routes/index"

const WebrtcRoute = WebrtcRouteImport.update({
  id: "/webrtc",
  path: "/webrtc",
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: "/signin",
  path: "/signin",
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: "/notifications",
  path: "/notifications",
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: "/messages",
  path: "/messages",
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: "/explore",
  path: "/explore",
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: "/auth",
  path: "/auth",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/auth": typeof AuthRoute
  "/explore": typeof ExploreRoute
  "/messages": typeof MessagesRoute
  "/notifications": typeof NotificationsRoute
  "/settings": typeof SettingsRoute
  "/signin": typeof SigninRoute
  "/webrtc": typeof WebrtcRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/auth": typeof AuthRoute
  "/explore": typeof ExploreRoute
  "/messages": typeof MessagesRoute
  "/notifications": typeof NotificationsRoute
  "/settings": typeof SettingsRoute
  "/signin": typeof SigninRoute
  "/webrtc": typeof WebrtcRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/auth": typeof AuthRoute
  "/explore": typeof ExploreRoute
  "/messages": typeof MessagesRoute
  "/notifications": typeof NotificationsRoute
  "/settings": typeof SettingsRoute
  "/signin": typeof SigninRoute
  "/webrtc": typeof WebrtcRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/auth"
    | "/explore"
    | "/messages"
    | "/notifications"
    | "/settings"
    | "/signin"
    | "/webrtc"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/auth"
    | "/explore"
    | "/messages"
    | "/notifications"
    | "/settings"
    | "/signin"
    | "/webrtc"
  id:
    | "__root__"
    | "/"
    | "/auth"
    | "/explore"
    | "/messages"
    | "/notifications"
    | "/settings"
    | "/signin"
    | "/webrtc"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ExploreRoute: typeof ExploreRoute
  MessagesRoute: typeof MessagesRoute
  NotificationsRoute: typeof NotificationsRoute
  SettingsRoute: typeof SettingsRoute
  SigninRoute: typeof SigninRoute
  WebrtcRoute: typeof WebrtcRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/webrtc": {
      id: "/webrtc"
      path: "/webrtc"
      fullPath: "/webrtc"
      preLoaderRoute: typeof WebrtcRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/signin": {
      id: "/signin"
      path: "/signin"
      fullPath: "/signin"
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/settings": {
      id: "/settings"
      path: "/settings"
      fullPath: "/settings"
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/notifications": {
      id: "/notifications"
      path: "/notifications"
      fullPath: "/notifications"
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/messages": {
      id: "/messages"
      path: "/messages"
      fullPath: "/messages"
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/explore": {
      id: "/explore"
      path: "/explore"
      fullPath: "/explore"
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/auth": {
      id: "/auth"
      path: "/auth"
      fullPath: "/auth"
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ExploreRoute: ExploreRoute,
  MessagesRoute: MessagesRoute,
  NotificationsRoute: NotificationsRoute,
  SettingsRoute: SettingsRoute,
  SigninRoute: SigninRoute,
  WebrtcRoute: WebrtcRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
